apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
    app: demo-voting-app
spec:
  ports:
    - port: 6379
      targetPort: 6369
  selector:
    name: result-app-pod
    app: demo-voting-app
 